version: "3.9"
services:
  php:
    image: php:devday
    ports:
      - "80:8000"
    volumes:
      - .:/code
    depends_on:
      - random-server
      - redis-server
    working_dir: /code
    command: ["-S", "0.0.0.0:8000"]
  random-server:
    image: mitchallen/random-server
  redis-server:
    image: redis
    volumes:
     - data:/data
volumes:
  data: {}
